---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  #- name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[hops_shibboleth::install]
      - recipe[hops_shibboleth::default]
    attributes:
